```{r}
library(abind)
library(foreach)
library(doParallel)

library(lattice)
library(ggplot2)
library(GPfit)
library(lhs)
library(laGP)
library(mlegp)
library(MRFA)

rm(list=ls())
```

```{r}
source('header.R')
```

```{r}
### Generate a surface of the function
p=6

a <- seq(from=0,to=1,by=0.017)
m <- length(a)
xx <- cbind(rep(a,each=m), rep(a,times=m))
xx <- cbind(xx,randomLHS(m^2,k=p-2))
y_mesh <-michal(xx)
mesh.data <- data.frame(y_mesh=y_mesh,x1=xx[,1],x2=xx[,2])
wireframe(y_mesh~x1*x2,data=mesh.data,xlab='x1',ylab='x2',zlab='y',main='true surface of michalewicz function',drape=T)

### Generate the training data set via maximinLHS
n = 200
x <- maximinLHS(n,k=p)
y <- michal(x)+runif(n,min=-0.02,max=0.02) # add noise
```

```{r}
active_true=c(1,2)
```

lagp method
```{r}
eps=sqrt(.Machine$double.eps)
gpi=newGPsep(x,y,d=0.1,g=0.1*var(y),dK=TRUE)
mle=mleGPsep(gpi,param="both",tmin=c(eps,eps),tmax=c(10,var(y)))
w=predGPsep(gpi,xx)
RMSPE_sd_lagp <- sqrt(mean((w$mean-y_mesh)^2))/sd(y_mesh)
cat("The standard root mean square percentage error of lagp method is",RMSPE_sd_lagp,"\n")
```

mlegp method
```{r}
mlegp_model=mlegp(x,y,nugget=1,parallel = TRUE)
y_pred=predict(mlegp_model,xx)
RMSPE_sd_mlegp=sqrt(mean((y_pred-y_mesh)^2))/sd(y_mesh)
cat("The standard root mean square percentage error of mlegp method is",RMSPE_sd_mlegp,"\n")

active_mlegp=which(mlegp_model$beta>0.01)
fp_mlegp=length(setdiff(active_mlegp,active_true))
fn_mlegp=length(setdiff(active_true,active_mlegp))
cat("The false positive of mlegp method is",fp_mlegp,"\n")
cat("The false negative of mlegp method is",fn_mlegp,"\n")
```

MRFA method
```{r}
MRFA_model=MRFA_fit(x,y,verbose=TRUE)
y_pred=predict(MRFA_model,xx,lambda=min(MRFA_model$lambda))$y_hat
RMSPE_sd_MRFA=sqrt(mean((y_pred-y_mesh)^2))/sd(y_mesh)
cat("The standard root mean square percentage error of MRFA method is",RMSPE_sd_MRFA,"\n")
  
active_MRFA=NULL
for (i in 1:length(MRFA_model$active.group)){
  for (j in 1:length(MRFA_model$active.group[[i]])){
    active_MRFA=c(active_MRFA,MRFA_model$active.group[[i]][[j]]$effect)
  }
}
active_MRFA=unique(active_MRFA)
fp_MRFA=length(setdiff(active_MRFA,active_true))
fn_MRFA=length(setdiff(active_true,active_MRFA))
cat("The false positive of MRFA method is",fp_MRFA,"\n")
cat("The false negative of MRFA method is",fn_MRFA,"\n")
```

optkernel method
```{r}
theta=seq(from=1,to=9,length=5)
theta=c(theta*10^-2,theta*10^-1,theta,theta*10,theta*10^2)
mu=c(0.005,0.01,0.02,0.05,0.1,0.5)

optK=optkernel_fun_loocv(x,y,mu=mu,theta=theta,max_active=4,heredity="strong",drop.tol=0.05,drop.tol2=0.05,stop.tol=0.005,stop2.tol=0.005,max_iter_1=1000,max_iter_2=1000,x.norm=FALSE)
optK_pred <- optkernel_pred(x,optK,newx=xx)

summary.optkernel(optK)

RMSPE_sd_opt=sqrt(mean((optK_pred-y_mesh)^2))/sd(y_mesh)
cat("The standard root mean square percentage error of optkernel method is",RMSPE_sd_opt,"\n")


  
active_opt=unique(which(optK$kernel_input,arr.ind = TRUE)[ ,2])
fp_opt=length(setdiff(active_opt,active_true))
fn_opt=length(setdiff(active_true,active_opt))
cat("The false positive of optkernel method is",fp_opt,"\n")
cat("The false negative of optkernel method is",fn_opt,"\n")
```

predicted surface of michalewicz function (through optkernel method)
```{r}
mesh.data <- data.frame(pred=optK_pred,x1=xx[,1],x2=xx[,2])
wireframe(pred~x1*x2,data=mesh.data,xlab='x1',ylab='x2',zlab='y',main='predicted surface of michalewicz function',drape=T)
```



