library(abind)
library(foreach)
library(doParallel)
library(fields)

source('optkernel_method_3.R')
source('optkernel_pred.R')
source('Michalewicz.R')
source('summary.R')
source('optkernel_method_loocv.R')
source('Michal_6.R')